dist: trusty
language: node_js
node_js:
- "stable"
before_script:
- npm install
before_deploy:
- npm run build
deploy:
  provider: surge
  project: ./build/
  domain: lethal-beetle.surge.sh 
  skip_cleanup: true
