name: Integrate

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    run: nvmrc=$(cat .nvmrc)
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: $nvmrc
    - run: npm ci
    - run: npm run test
    - run: npm run build